dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
jobs:
  include:
   - stage: build
     name: "Build product"
     script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
   - stage: test
     name: "Test version"
     script: ./mvnw test -B
   - stage: publish
     name: "Publish docker image"
     script: 
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/spring-petclinic .
      - docker images
      - docker push $DOCKER_USERNAME/spring-petclinic
   - stage: deploy
     name: Deploy heroku
     script: skip 
     deploy: &heroku
      provider: heroku 
      api_key:
        secure: $HEROKU_KEY
      app: spring-pet
      on:
        repo: gabriel-joe/spring-petclinic

          