dist: trusty
language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: e1803e5e-2239-466c-838e-ba11ac43ea3f
  app: spring-pet
  on:
    repo: gabriel-joe/spring-petclinic
          