#!/bin/bash

if ( -z "$DOCKER_USERNAME" )
    then
      echo -e "\tSkipping docker publish because missing variable $DOCKER_USERNAME"
      exit 0
else
    echo -e "\tExecuting docker publishing"
fi


set -ev
sudo apt-get update -y
sudo apt-get install libxml2-utils -y
export DOCKER_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="properties"]/*[local-name()="docker-version"]/text()' pom.xml)
app_name="spring-petclinic"
app_image="${DOCKER_USERNAME}/${app_name}:${DOCKER_VERSION}"

unset DOCKER_CERT_PATH
unset DOCKER_HOST
unset DOCKER_TLS
unset DOCKER_TLS_VERIFY

docker build -t "${app_image}" .
docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
docker images
docker push "${app_image}"

exit 0