version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_PASSWORD=petclinic
      - MYSQL_USER=gabriel
      - MYSQL_DATABASE=petclinic
      - MYSQL_ROOT_PASSWORD=petclinic
    ports:
      - '3306:3306'
    
  web:
    image: 'gabrieljoe/spring-petclinic:latest'
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.99.100/petclinic?useSSL=false&allowPublicKeyRetrieval=true
      
networks:
  default:
    

