version: '3'
services:
  sonarqube:
    image: 'gabrieljoe/sonarqube-petclinic:latest'
    ports:
      - '9000:9000'
    command:
       - -Dsonar.ce.javaOpts=-Xmx2048m -Dsonar.web.javaOpts=-Xmx2048m
    
  nexus-v3:
    image: 'gabrieljoe/nexusv3-petclinic:latest'
    ports:
      - '8081:8081'
  jenkins:
    image: 'gabrieljoe/jenkins-petclinic:latest'
    ports:
      - '8080:8080'
      - '50000:50000'
      
    

