version: '3'
services:
  sonarqube:
    image: 'gabrieljoe/sonarqube-petclinic:latest'
    ports:
      - '9000:9000'
    volumes:
       - sonar-data:/home/sonarqube
    
  nexus-v3:
    image: 'gabrieljoe/nexusv3-petclinic:latest'
    ports:
      - '8081:8081'
    volumes:
       - nexus-data:/nexus-data
  jenkins:
    image: 'gabrieljoe/jenkins-petclinic:latest'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
       - jenkins-data:/var/jenkins_home
      
    

